# Generated by Django 3.0.6 on 2020-06-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('category_or_job_function', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('featured', models.CharField(max_length=5)),
                ('full_time_or_part_time', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('working_hours', models.CharField(max_length=5)),
            ],
        ),
    ]
