# Generated by Django 3.0.6 on 2020-05-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availablejob_bussiness_bussinessservice_client_industry_jobalert_jobtype_keyword_location_service_su'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinessservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bussinessservice',
            name='updated_at',
        ),
    ]
