# Generated by Django 3.0.6 on 2020-05-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200529_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablejob',
            name='salary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
