# Generated by Django 3.0.6 on 2020-05-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200529_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
