# Generated by Django 3.0.6 on 2020-05-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200529_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(height_field=533, upload_to='', width_field=800),
        ),
    ]
