# Generated by Django 3.0.6 on 2020-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
